{% set name = "blessed" %}
{% set version = "1.18.0" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 1312879f971330a1b7f2c6341f2ae7e2cbac244bfc9d0ecfbbecd4b0293bc755

build:
  number: 0
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python
  run:
    - backports.functools_lru_cache >=1.2.1  # [py<32]
    - jinxed >=0.5.4  # [win]
    - ordereddict ==1.1  # [py<27]
    - python
    - six >=1.9.0
    - wcwidth >=0.1.4

test:
  imports:
    - blessed
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://pypi.org/project/blessed/
  summary: Easy, practical library for making terminal apps, by providing an elegant, well-documented interface to Colors, Keyboard input, and screen Positioning capabilities.
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - hadim
