{% set name = "blessed" %}
{% set version = "1.23.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 56591a32966f704f6131f1400af4151d9e8f5f4144133a5ca034019763dee77b

build:
  number: 0
  script: {{ PYTHON }} -m pip install . --no-deps --no-build-isolation --ignore-installed --no-cache-dir -vv
  skip: true  # [py<37]

requirements:
  host:
    - pip
    - python
    - flit-core >=3.11,<4
  run:
    - jinxed >=1.1.0  # [win]
    - python
    - six >=1.9.0
    - wcwidth >=0.1.4

#AssertionError: assert 0.1948099136352539 <= 0.18')
{% set ignore_test = "" %} # [not osx]
{% set ignore_test = "--ignore=tests/test_sixel.py" %} # [osx]
test:
  source_files:
    - tests
  imports:
    - blessed
  commands:
    - pip check
    - pytest -v tests {{ignore_test}}
  requires:
    - pip
    - pytest

about:
  home: https://pypi.org/project/blessed
  summary: Easy, practical library for making terminal apps, by providing an elegant, well-documented interface to Colors, Keyboard input, and screen Positioning capabilities.
  description: Easy, practical library for making terminal apps, by providing an elegant, well-documented interface to Colors, Keyboard input, and screen Positioning capabilities.
  license: MIT
  license_family: MIT
  license_file: LICENSE
  dev_url: https://github.com/jquast/blessed
  doc_url: https://github.com/jquast/blessed

extra:
  recipe-maintainers:
    - hadim
    - mattip
