{% set name = "blessed" %}
{% set version = "1.47.0" %}
{% set ignore_test = "" %}
{% set ignore_test = ignore_test + " --ignore=tests/test_sixel.py" %}  # [osx]

#AssertionError: assert 0.1948099136352539 <= 0.18')
package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: ea13e06ae40f24710325411c5fa9b689d215cf170276cf1fda41feddaec8d3e0

build:
  number: 0
  script: {{ PYTHON }} -m pip install . --no-deps --no-build-isolation --ignore-installed --no-cache-dir -vv
  skip: true  # [py<38]

requirements:
  host:
    - pip
    - python
    - flit-core >=3.11,<4
  run:
    - jinxed >=1.1.0  # [win]
    - python
    - six >=1.9.0
    - wcwidth >=0.8.1

test:
  source_files:
    - tests
  imports:
    - blessed
  commands:
    - pip check
    - pytest -v tests {{ignore_test}}
  requires:
    - pip
    - pytest

about:
  home: https://pypi.org/project/blessed
  summary: Easy, practical library for making terminal apps, by providing an elegant, well-documented interface to Colors, Keyboard input, and screen Positioning capabilities.
  description: Easy, practical library for making terminal apps, by providing an elegant, well-documented interface to Colors, Keyboard input, and screen Positioning capabilities.
  license: MIT
  license_family: MIT
  license_file: LICENSE
  dev_url: https://github.com/jquast/blessed
  doc_url: https://github.com/jquast/blessed

extra:
  recipe-maintainers:
    - hadim
    - mattip
